/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dono' at '16-8-22 下午10:35' with Gradle 3.0
 *
 * @author dono, @date 16-8-22 下午10:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
